name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: pip install flask && pip install request && npm install request

      - name: Start server
        run: lscpu

      - name: Wait for server to start
        run: sleep 5

      - name: Set up ngrok
        uses: LuisBoto/ngrok-tunnel-action@v0.1.7.2
        with:
          timeout: 50h
          port: 3000
          ngrok_authtoken: 2Vag9FSSlCxp2hJvlcY6vDXoeCX_5jwJXvmQkWwpY2TgLVhux
          tunnel_type: http
          save_url_to_filename: tunnelURL.md

      - name: Get ngrok URL
        run: |
          echo "Ngrok URL: ${{ steps.ngrok.outputs.ngrok_url }}"

      - name: Run tests
        run: python api.py

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build
